[package]
name = "commits-of-interest-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
crossterm = "0.29"
git2 = "0.20"
ratatui = "0.30"
commits-of-interest-core = { path = "../core" }

[lints.rust.unexpected_cfgs]
level = "deny"
check-cfg = ["cfg(dylint_lib, values(any()))"]
