[package]
name = "commits-of-interest-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
git2 = "0.20"
serde_json = "1.0"

[lints.rust.unexpected_cfgs]
level = "deny"
check-cfg = ["cfg(dylint_lib, values(any()))"]
